### ISSUE TITLE
"Bad Request: message text is empty"

### ISSUE THREAD

**Issue by ubsoftchanel** [manzoorwanijk/telegram-bot-api-worker#1]
Hi

when i use
https://bypasstel1.cbvbln.workers.dev/botxxxxxxxxxxxxxxxx1qZFKHPFtLh6NchPGDbMhPK00/sendmessage?chat_id=481965030&text=test

i get
{"ok":false,"error_code":400,"description":"Bad Request: message text is empty"}

how fix this? I need bot send a message to me.

(token and chat-id changed! dont test with them)

**Comment by manzoorwanijk** [comment]
@ubsoftchanel the issue has been fixed via #2. Please copy the code again and then Save and Deploy.
